services:
  - docker

before_script:
  - docker image ls
  - docker ps -a
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # base image
  - cd $TRAVIS_BUILD_DIR/base
  - docker build -t base-img .
  - docker tag base-img byhuang/ubuntu-dev:base
  - docker push byhuang/ubuntu-dev:base
  # personal image
  - cd $TRAVIS_BUILD_DIR/user
  - docker build -t user-img .
  - docker tag user-img byhuang/ubuntu-dev:user
  - docker push byhuang/ubuntu-dev:user

after_success:
  - docker image ls
  - docker ps -a

notifications:
  email: false

