services:
  - docker

before_install:
  - docker image ls

install:
  - docker build -t local-img .
  - docker image ls

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag local-img byhuang/ubuntu-dev:latest
  - docker push byhuang/ubuntu-dev:latest

email:
  false

